//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BulkEmailMarketing
{
    using System;
    using System.Collections.Generic;
    
    public partial class campaignTable
    {
        public int campaignid { get; set; }
        public string canpaign_name { get; set; }
        public string campaign_from { get; set; }
        public string attachmentcode { get; set; }
        public string email_body { get; set; }
        public string campaign_subject { get; set; }
    }
}
